Support Activity Player runnable urls for imported activities
concord-consortium/report-service pull request #50
Opened 2021-05-12 16:09 UTC by sfentress

Activity Player activities that have been imported from LARA have a resource url like

https://activity-player.concord.org/?activity=https%3A%2F%2Fauthoring.staging.concord.org%2Fapi%2Fv1%2Factivities%2F20753.json&firebase-app=report-service-dev

this changes the above to

https://authoring.staging.concord.org/activities/20753

so that the resource be properly returned by the report service api.

2021-05-13 15:28 UTC, mklewandowski approved these changes
👍

2021-05-14 17:04 UTC, scytacki requested changes
This won't support sequences. Here is an example which supports sequences:
https://github.com/concord-consortium/activity-player/blob/f74895f15728d7aa72d228653496b43066845bb7/src/lara-api.ts#L5-L15

2021-05-18 18:35 UTC, sfentress commented
Hi @scytacki , sorry, I missed this earlier. This is updated now.

2021-05-18 20:22 UTC, scytacki approved these changes
looks good to me.

2021-05-18 20:22 UTC, merged