Add model urls to Athena query
concord-consortium/report-service pull request #92
Opened 2021-07-23 19:43 UTC by sfentress

This constructs a url to the Portal Report for every iframe interactive, if the user has answer data for the model.

The url that is constructed looks like:

```
https://portal-report.concord.org/branch/master/index.html
  ?auth-domain=[https://learn.staging.concord.org | https://learn.concord.org | other portal url]
  &firebase-app=[report-service-dev | report-service-pro]
  &iframeQuestionId=[model-id, eg. "mw_interactive_210741"]
  &class=[{portal-url}/api/v1/classes/{class-id}]
  &offering=[{portal-url}/api/v1/offerings/{offering-id}]
  &studentId=[student-id]
```

For this to work we need the `offering-id`, which wasn't previously passed back from the portal when requesting learner details, and has now been added as a PR. The leaners table must also be updated to support this.

An example query that can be run in Athena as `AdminConcordQA` is

```
-- id activity-activity_20811
-- name Sam's GeoCode test
-- type activity

WITH activities AS ( SELECT *, cardinality(questions) AS num_questions FROM "report-service"."activity_structure" WHERE structure_id = 'f6363e70-c366-4e02-82db-0b42fc9853f4' ),

grouped_answers AS ( SELECT l.run_remote_endpoint remote_endpoint, map_agg(a.question_id, a.answer) kv1, map_agg(a.question_id, a.submitted) submitted
  FROM "report-service"."partitioned_answers" a
  INNER JOIN "report-service"."learners" l
  ON (l.query_id = 'f6363e70-c366-4e02-82db-0b42fc9853f4' AND l.run_remote_endpoint = a.remote_endpoint)
  WHERE a.escaped_url = 'https---authoring-staging-concord-org-activities-20811'
  GROUP BY l.run_remote_endpoint ),

learners_and_answers AS ( SELECT run_remote_endpoint remote_endpoint, runnable_url, learner_id, student_id, user_id, offering_id, student_name, username, school, class, class_id, permission_forms, last_run, teachers, grouped_answers.kv1 kv1, grouped_answers.submitted submitted,
  IF (kv1 is null, 0, cardinality(array_intersect(map_keys(kv1),map_keys(activities.questions)))) num_answers
  FROM activities, "report-service"."learners" l
  LEFT JOIN grouped_answers
  ON l.run_remote_endpoint = grouped_answers.remote_endpoint
  WHERE l.query_id = 'f6363e70-c366-4e02-82db-0b42fc9853f4' )

SELECT
  null AS remote_endpoint,
  null AS runnable_url,
  null AS learner_id,
  null AS student_id,
  null AS user_id,
  null AS student_name,
  null AS username,
  null AS school,
  null AS class,
  null AS class_id,
  null AS permission_forms,
  null AS last_run,
  null AS teacher_user_ids,
  null AS teacher_names,
  null AS teacher_districts,
  null AS teacher_states,
  null AS teacher_emails,
  null AS num_questions,
  null AS num_answers,
  null AS percent_complete,
  null AS mw_interactive_210741_json,
  null AS mw_interactive_210741_url,
  null AS mw_interactive_210742_json,
  null AS mw_interactive_210742_url
FROM activities

UNION ALL

SELECT
  remote_endpoint,
  runnable_url,
  learner_id,
  student_id,
  user_id,
  student_name,
  username,
  school,
  class,
  class_id,
  permission_forms,
  last_run,
  array_join(transform(teachers, teacher -> teacher.user_id), ',') AS teacher_user_ids,
  array_join(transform(teachers, teacher -> teacher.name), ',') AS teacher_names,
  array_join(transform(teachers, teacher -> teacher.district), ',') AS teacher_districts,
  array_join(transform(teachers, teacher -> teacher.state), ',') AS teacher_states,
  array_join(transform(teachers, teacher -> teacher.email), ',') AS teacher_emails,
  activities.num_questions AS num_questions,
  num_answers,
  round(100.0 * num_answers / activities.num_questions, 1) AS percent_complete,
  kv1['mw_interactive_210741'] AS mw_interactive_210741_json,
  CASE WHEN kv1['mw_interactive_210741'] IS NULL THEN '' ELSE concat('https://portal-report.concord.org/branch/master/index.html?auth-domain=https%3A%2F%2Flearn.staging.concord.org&firebase-app=report-service-dev&iframeQuestionId=mw_interactive_210741&class=https%3A%2F%2Flearn.staging.concord.org%2Fapi%2Fv1%2Fclasses%2F', cast(class_id as varchar), '&offering=https%3A%2F%2Flearn.staging.concord.org%2Fapi%2Fv1%2Fofferings%2F', cast(offering_id as varchar), '&studentId=', cast(user_id as varchar)) END AS mw_interactive_210741_url,
  kv1['mw_interactive_210742'] AS mw_interactive_210742_json,
  CASE WHEN kv1['mw_interactive_210742'] IS NULL THEN '' ELSE concat('https://portal-report.concord.org/branch/master/index.html?auth-domain=https%3A%2F%2Flearn.staging.concord.org&firebase-app=report-service-dev&iframeQuestionId=mw_interactive_210742&class=https%3A%2F%2Flearn.staging.concord.org%2Fapi%2Fv1%2Fclasses%2F', cast(class_id as varchar), '&offering=https%3A%2F%2Flearn.staging.concord.org%2Fapi%2Fv1%2Fofferings%2F', cast(offering_id as varchar), '&studentId=', cast(user_id as varchar)) END AS mw_interactive_210742_url
FROM activities, learners_and_answers
```

This creates two urls for the two learners with models, one of which is

https://portal-report.concord.org/branch/master/index.html?auth-domain=https%3A%2F%2Flearn.staging.concord.org&firebase-app=report-service-dev&iframeQuestionId=mw_interactive_210741&class=https%3A%2F%2Flearn.staging.concord.org%2Fapi%2Fv1%2Fclasses%2F8&offering=https%3A%2F%2Flearn.staging.concord.org%2Fapi%2Fv1%2Fofferings%2F1693&studentId=4652

This requires being logged in as an admin or the class teacher (I believe).

(Note: The query above works because I edited the learner JSON in S3 by hand to include the offering-id. Queries on learn.staging won't otherwise work until the portal PR is brought into staging.)

2021-07-23 19:44 UTC, sfentress commented
The Rigse PR that is needed is https://github.com/concord-consortium/rigse/pull/1054

2021-07-27 16:08 UTC, scytacki requested changes
Looks good overall. 

Suggested fixes:
- uppercasing SQL
- add full SQL to the tests, or at least add a test specific to the `createModelUrl` function.

2021-07-28 18:59 UTC, sfentress commented
This is updated with

* Correctly-cased SQL
* SQL generation in aws.js
* Portal Report url now an environment parameter, with a default in the deploy script
* Tests correctly asset SQL for url formation

2021-07-29 13:59 UTC, scytacki approved these changes
Looks good to me. I'm going to go ahead and merge it.

I think there might be an issue with the `sourceKey` or `answerSourceKey` being needed by the portal report. But perhaps it can automatically figure it out from what it has. If it is an issue then I think the query-creator can figure out the right value from the information it has and add that to the URL.

learn.staging.concord.org has the offering_id change, so it should be possible to test this on staging.

2021-07-29 14:03 UTC, scytacki requested changes
Oh actually there is a merge conflict. A little while back I added the env.json approach to manage variables, that removes the need to set values of variables in the template itself. 

It looks like this PR was branched off before that change.

2021-07-29 15:43 UTC, merged